name: snyk-vulnerability-assessment
on: push
env:
    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    DATADOG_API_KEY: ${{ secrets.DD_API_KEY }}
    DATADOG_APP_KEY: ${{ secrets.DD_APP_KEY }}
jobs:
    vulnerability_analysis:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
            java-version: 12
            java-package: jre
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Datadog CI
        run: npm install -g --save-dev @datadog/datadog-ci
        shell: bash
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: -d --severity-threshold=high
      - uses: datadog/github-action-vulnerability-analysis@master
        with:
          build-file: 'pom.xml'
          service: 'javaGoof'
          version: 'v2.1'
          datadog-api-key: ${{ secrets.DD_API_KEY }}
          datadog-app-key: ${{ secrets.DD_APP_KEY }}
          snyk-token: ${{ secrets.SNYK_TOKEN }}
